Repository bcgov/jag-document-utils, pull requests merged in 2020-11, with the labels that each got.

#7 initial commit
  src/.gitignore
  src/README.md
  src/Still_to_be_done.txt
  src/payload_design/ReadMe.txt
  src/payload_design/pdf_merge_request.json
  src/payload_design/pdf_merge_response_fail.json
  src/payload_design/pdf_merge_response_success.json
  src/pom.xml
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/DocumentMergeServiceApplication.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/config/ConfigProperties.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/controller/MergeController.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/exception/DocMergeExceptionHandler.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/exception/MergeException.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/model/DocMergeRequest.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/model/DocMergeResponse.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/model/Document.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/model/JSONError.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/model/JSONResponse.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/model/MergeDoc.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/model/Options.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/service/MergeService.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/service/MergeServiceImpl.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/swagger2/SwaggerAPIConfig.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/swagger2/SwaggerConfig.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/utils/Base64Utils.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/utils/DDXUtils.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/utils/DocMergeConstants.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/utils/DocMergeUtils.java
  src/src/main/java/ca/bc/gov/open/pssg/docmerge/utils/PDFBoxUtilities.java
  src/src/main/resources/application.properties
  src/src/main/resources/logback.xml
  src/src/test/java/ca/bc/gov/open/pssg/docmerge/DocumentMergeServiceApplicationTests.java
  src/test_files/ReadMe.txt
  src/test_files/RecordOfProceedings_1.5.dat
  src/test_files/RecordOfProceedings_1.5.pdf
  src/test_files/outtest1.dat
  src/test_files/outtest1.pdf
  src/test_files/outtest2.dat
  src/test_files/outtest2.pdf
  src/test_files/pdfsample.pdf
  src/test_files/pdfsample1.dat
  src/test_files/pdfsample1.pdf
  src/test_files/pdfsample2.dat
  src/test_files/pdfsample2.pdf
Labels: porkshop sandwiches

#15 more tests
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/DocumentMergeServiceApplication.java
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/adobe/AdobeConfig.java
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/controller/MergeController.java
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/exception/DocMergeExceptionHandler.java
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/exception/MergeException.java
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/service/MergeServiceImpl.java
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/utils/PDFBoxUtilities.java
  src/document-merge-api/src/test/java/ca/bc/gov/open/pssg/docmerge/DocumentMergeServiceApplicationTests.java
  src/document-merge-api/src/test/java/ca/bc/gov/open/pssg/docmerge/adobe/AdobeConfigTest.java
  src/document-merge-api/src/test/java/ca/bc/gov/open/pssg/docmerge/service/MergeServiceImplTest.java
Labels: porkshop sandwiches

#22 Initial refactor update
  src/README.md
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/adobe/AdobeConfig.java
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/controller/MergeController.java
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/service/MergeServiceImpl.java
  src/document-merge-api/src/main/java/ca/bc/gov/open/pssg/docmerge/utils/DDXUtils.java
Labels: DO NOT MERGE

#25 Update code-climate-test-coverage.yaml
  .github/workflows/code-climate-test-coverage.yaml
Labels: git

#30 Adding test for xfa document
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/utils/PDFBoxUtilities.java
  src/document-utils-api/src/test/java/ca/bc/gov/open/jag/documentutils/TestHelpers.java
  src/document-utils-api/src/test/java/ca/bc/gov/open/jag/documentutils/service/MergeServiceImplTest.java
  src/document-utils-api/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: porkshop sandwiches

#32 Returning consistent api errors
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/Keys.java
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/api/DocumentController.java
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/exception/DocMergeExceptionHandler.java
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/exception/MergeException.java
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/model/ApiError.java
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/model/Document.java
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/model/JSONError.java
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/model/JSONResponse.java
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/service/MergeServiceImpl.java
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/utils/DocMergeUtils.java
  src/document-utils-api/src/main/java/ca/bc/gov/open/jag/documentutils/utils/PDFBoxUtilities.java
  src/document-utils-api/src/test/java/ca/bc/gov/open/jag/documentutils/controller/DocumentControllerTest.java
  src/document-utils-api/src/test/java/ca/bc/gov/open/jag/documentutils/service/MergeServiceImplTest.java
Labels: porkshop sandwiches

#34 Add missing test
  src/document-utils-api/src/test/java/ca/bc/gov/open/jag/documentutils/swagger2/SwaggerConfigTest.java
Labels: porkshop sandwiches

#45 added repository name back
  .github/workflows/build-image.yaml
  .github/workflows/build-release-image.yaml
Labels: git
